### ISSUE TITLE
Add ability to remove a cert

### ISSUE THREAD

**Issue by timmeade** [CumberlandGroup/docker-haproxy-certbot#6]
Is there a way to remove a cert from the system?   

For example if we are using foo.com and it's renewing successfully and then we want to move foo.com to another load balancer, now this will error on the renewals.

**Comment by nmarus** [comment]
I should probably insert a script to do this, but you can simple remove|move the entry from the directory `/etc/letsencrypt/live` (or the path that directory is mapped to outside of docker) and it will no longer renew.
